### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by eduardokraus** [dthies/moodle-mod_plenum#2]
please review and clean up your code, and remove unused variables, DB calls, etc.

![Captura de Tela 2024-10-19 às 08 58 59](https://github.com/user-attachments/assets/6a1cd510-ce52-46f6-9892-3b4c1b7e251b)
![Captura de Tela 2024-10-19 às 08 59 24](https://github.com/user-attachments/assets/2d28c800-1f2d-417e-ade8-fcefe4d726b0)

**Comment by dthies** [comment]
Eduardo I fixed the first one of those. The second is explained in the comments there.  This is because subplugin settings files are included. This is the way it is done in other modules. I agree it is a violation, but  seems to be necessary to be consistent with the legacy settings code.
