### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by eduardokraus** [dthies/moodle-mod_plenum#3]
According to Moodle standards, all custom classes that are not part of the core API should be placed in the 'classes/local' folder to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)

Additionally, please review the rules for level 2 namespaces:
[Level 2 Namespaces](https://moodledev.io/general/development/policies/codingstyle#rules-for-level2)

**Comment by dthies** [comment]
Thanks again for the review, but I am not sure I understand what you are referring to specifically here. The Level 2 Namespaces do match core systems: admin  completion event external form grades hook  output plugininfo privacy search. The top level classes are  Level 1 namespace so they are allowed.  Maybe you are questioning hook  namespace which was added as a core namespace very recently.
