### ISSUE TITLE
validate lower than 2.9

### ISSUE THREAD

**Issue by eduardokraus** [dthies/moodle-mod_plenum#5]
Your plugin only supports Moodle 4.5.0 but you validate lower than 2.9?

![Captura de Tela 2024-10-19 às 09 18 02](https://github.com/user-attachments/assets/267f88c6-acd1-4fc0-a34f-e2f027394394)

**Comment by dthies** [comment]
Thank you very much Eduado for looking and this I just created a new version with this older code removed. This should be fixed.
